model:
  name: deeplabv3plus
  input_channels: 17
  out_channels: 1
  pretrained: false
  arch: deeplabv3plus_resnet50
  output_stride: 8
  pretrained_backbone: false
data:
  mode: 2d
  train_path: ../../../processed_17ch_dce/train
  val_path: ../../../processed_17ch_dce/val
  test_path: ../../../processed_17ch_dce/test
  raw_dataset_root: ../../../seg
  image_size:
  - 256
  - 256
  normalize: zscore
train:
  epochs: 100
  batch_size: 4
  lr: 0.0001
  weight_decay: 1.0e-05
  num_workers: 4
  early_stopping: 0
  scheduler: reduce_on_plateau
  amp: true
  max_grad_norm: 1.0
  seed: 2026
eval:
  threshold: 0.5
  save_predictions: false
output:
  checkpoint_dir: checkpoints
  test_dir: test_results
  log_file: training_log.csv
