model:
  name: plhn
  input_channels: 1
  out_channels: 1
  pretrained: false
  base_channels: 32
  hidden_size: 256
  transformer_layers: 8
data:
  mode: 3d
  train_path: ../../../processed_17ch_dce/train
  val_path: ../../../processed_17ch_dce/val
  test_path: ../../../processed_17ch_dce/test
  raw_dataset_root: ../../../seg
  cache_root: ../../dataset/processed_3d_preonly/plhn
  patch_size:
  - 48
  - 128
  - 128
  samples_per_volume: 4
  positive_crop_prob: 0.7
  normalize: zscore
  label_phase: null
  allow_missing_phases: false
  input_phase_indices:
  - 0
  phase_names:
  - VIBRANT
train:
  epochs: 100
  batch_size: 8
  lr: 0.0001
  weight_decay: 1.0e-05
  num_workers: 2
  early_stopping: 0
  scheduler: reduce_on_plateau
  amp: true
  seed: 2026
eval:
  threshold: 0.5
  save_predictions: false
  sliding_window_overlap: 0.5
output:
  checkpoint_dir: checkpoints_preonly
  test_dir: test_results_preonly
  log_file: training_log_preonly.csv
